Add automated testing
Tiny-Home-Consulting/Dependiject pull request #10
Opened 2022-05-24 18:22 UTC by bbrk24

## Issue Link

Fixes #9

## Overview of Changes

This PR adds automated tests, and fixes an issue in `MultitypeService` found while testing.

### Anything you want to highlight?

N/A

## Test Plan

In the terminal, while inside the root directory of the repository, just run `swift test`. It should automatically compile the library and run the tests.

2022-05-24 18:48 UTC, bbrk24 commented
Could this PR justify the removal of the "Test Plan" section from the PR template?

2022-06-01 13:35 UTC, wboyd600 requested changes

2022-06-01 13:35 UTC, wboyd600 commented on Tests/MultitypeServiceTests.swift
> +        _ = Factory.shared.resolve(C.self)
We could verify that `registration.type == C.self`. I think I get the point of the test, passing if it doesn't `fatalError()` resolving C but it might add some clarity

2022-06-01 13:35 UTC, wboyd600 commented on Tests/RegistrationNameTests.swift
> +        // _ = Factory.shared.resolve(String.self, name: "3")
I feel like this doesn't need to be in the tests since we've documented how it is supposed to work.

2022-06-01 13:35 UTC, wboyd600 commented on Tests/MultitypeServiceTests.swift
> +        _ = Factory.shared.resolve(C.self)
Or saying check that it doesn't throw a fatalError

2022-06-09 20:29 UTC, wboyd600 approved these changes

2022-09-06 17:23 UTC, merged