Make @Store default to RunLoop.main
Tiny-Home-Consulting/Dependiject pull request #12
Opened 2022-08-25 18:05 UTC by bbrk24

## Issue Link

Fixes #11

## Overview of Changes

This PR adds an optional Scheduler argument to `@Store` which defaults to `RunLoop.main`, so the user can specify where to receive updates.

### Anything you want to highlight?

I'm not 100% sure on the licensing implications, see the issue for details.

## Test Plan

The example apps have been changed so this is now necessary. If you change the code so that the view does not receive updates on the main thread, either by reverting the changes to `@Store` or by modifying the view as follows:

```diff
 import SwiftUI
 import Dependiject
+import Combine
 
 struct ContentView: View {
-    @Store var viewModel = Factory.shared.resolve(ContentViewModel.self)
+    @Store(on: ImmediateScheduler.shared) var viewModel = Factory.shared.resolve(ContentViewModel.self)
```

then clicking the "fetch new data" button will cause a runtime warning not to publish UI updates from a background thread.

2022-08-25 19:26 UTC, wboyd600 requested changes
I was able to test the changes and verify that the `@Store` changes fix the publishing UI changes from the background thread issue.

Only requesting changes on 1 byte (I actually have no idea how github stores chars but there is one extra space I think.)

2022-08-25 19:26 UTC, wboyd600 commented on iOS 14 Example/Dependiject_Example/ContentViewModel.swift
> +     func refreshData() async {
Extra space

2022-08-25 19:26 UTC, wboyd600 commented on iOS 14 Example/Dependiject_Example/Services.swift
> +        // Not noticeably long, but enough to potentially change threads
Were you able to get the warning appear before the changes to `@Store` ? 

EDIT:
I tested it with `ImmediateScheduler.shared` and was able to get the warning and verify the `@Store` changes fixes the original issue

2022-08-25 19:41 UTC, wboyd600 approved these changes

2022-09-02 20:52 UTC, Ljgleeson approved these changes

2022-09-02 20:52 UTC, Ljgleeson commented on iOS 13 Example/Dependiject/Services.swift
> +        try? await Task.sleep(nanoseconds: 1000)
I tried to see if theres a consensus for how long a task should sleep for thread management but didn't really find much. I don't think the specific amount will matter to much so 1000 nanoseconds works for me

2022-09-02 21:06 UTC, bbrk24 commented on iOS 13 Example/Dependiject/Services.swift
> +        try? await Task.sleep(nanoseconds: 1000)
I've looked at the implementation for `sleep(nanoseconds:)` ([here](https://github.com/apple/swift/blob/6c313ab21bc3b904bfc88b609e3623357e38632a/stdlib/public/Concurrency/TaskSleep.swift#L204) if you're curious, but it's a bit hard to read) and it looks like it just enqueues a job with the specified delay. Since it always starts a new job, the number can be as small as we want -- I just tested it and even just `0` will cause a jump to a different thread.

2022-09-06 14:31 UTC, wboyd600 commented on iOS 13 Example/Dependiject/Services.swift
> +        try? await Task.sleep(nanoseconds: 1000)
@Ljgleeson Ultimately the time in there shouldn't matter. Remove the `RunLoop.main` and this will warn you about publishing from a background thread.

2022-09-06 15:24 UTC, lawhorkl approved these changes

2022-09-06 17:11 UTC, merged