Document @Store
Tiny-Home-Consulting/Dependiject pull request #14
Opened 2022-09-06 20:15 UTC by bbrk24

## Issue Link

Fixes #13

## Overview of Changes

This PR rewrites the `Store` struct to be fully documented and within our style guide.

### Anything you want to highlight?

N/A
## Test Plan

Look at the documentation after running `./dochost.sh` or generating it in Xcode with Ctrl-Cmd-Shift-D.

2022-09-06 20:57 UTC, NicholasChase approved these changes

2022-09-07 15:23 UTC, Ljgleeson approved these changes

2022-09-07 19:29 UTC, wboyd600 requested changes
Most of the comments would fall into the 'comment' category but the `stored on the main thread` doesn't really make sense

2022-09-07 19:29 UTC, wboyd600 commented on Dependiject/Store.swift
> +/// Use this property wrapper to wrap observables which are injected. Unlike `StateObject`, this
"Use this property wrapper to wrap injected observable objects."

2022-09-07 19:29 UTC, wboyd600 commented on Dependiject/Store.swift
> +/// does not have any constraints at compile-time, which allows the wrapped type to be a protocol.
"this (this what?) does not have any compile-time constraints,"

"allowing the wrapped type to be a protocol"  ? maybe

2022-09-07 19:29 UTC, wboyd600 commented on Dependiject/Store.swift
> +/// enforced at compile-time, this is enforced at runtime.
"This is not enforced at compile time." You already said it's enforced at runtime

2022-09-07 19:29 UTC, wboyd600 commented on Dependiject/Store.swift
> +/// Injected objects which are not observable do not need to be given a property wrapper.
I feel like this would be in some other documentation (like this already said it's for observable objects). Maybe like a see-also on Factory.resolve or examples of how to use it there for observables and non-observables

2022-09-07 19:29 UTC, wboyd600 commented on Dependiject/Store.swift
> +    /// Create a value that is stored on the main thread.
I don't know if 'stored' on the main thread really makes sense. It's events are received on the main thread, but nothing can really be stored on a thread

2022-09-07 19:29 UTC, wboyd600 commented on Dependiject/Store.swift
> +    /// Use this init when it is not desirable to always present updates on the main thread. This
"Use this init to [etc.] on a specific scheduler other than `RunLoop.main`"

2022-09-08 14:40 UTC, wboyd600 approved these changes

2022-09-08 14:41 UTC, merged