Allow documentation to run on any port
Tiny-Home-Consulting/Dependiject pull request #16
Opened 2022-09-07 16:34 UTC by bbrk24

## Issue Link

Fixes #15

## Overview of Changes

Rather than always running on port 3000, the documentation server now runs on the port specified by the `DOC_PORT` environment variable. See the README for an example.

If the port is specified as 0, or not specified at all, hapi will search for an available port.

### Anything you want to highlight?

The `??` operator in JavaScript was introduced in node 14, and the documentation server is compatible with node 12. To avoid breaking node 12 compatibility, I have used `||` instead.

It appears that hapi 21 will require node 14 anyways, so if and when we upgrade from hapi 20 to hapi 21, this `||` can be changed to `??`. 

## Test Plan

Run the dochost script in the terminal with various values for `DOC_PORT`.

2022-09-07 17:05 UTC, NicholasChase approved these changes

2022-09-07 17:31 UTC, Ljgleeson approved these changes
Tested and performed as expected

2022-09-07 18:01 UTC, noahmehl requested changes

2022-09-07 18:01 UTC, noahmehl commented on docserver/index.js
> +        port: process.env.DOC_PORT || 0
The default port shouldn't be 0, then it will fail to run?

2022-09-07 18:09 UTC, bbrk24 commented on docserver/index.js
> +        port: process.env.DOC_PORT || 0
To hapi, port `0` means "find an available port and use that". From my testing it tends to select a rather high port, such as `62743`. However, I was always able to access it in the browser.

2022-09-07 18:10 UTC, noahmehl commented on docserver/index.js
> +        port: process.env.DOC_PORT || 0
Works for me!

2022-09-07 18:10 UTC, noahmehl approved these changes

2022-09-08 14:55 UTC, wboyd600 reviewed
Changelog?

2022-09-08 15:17 UTC, wboyd600 approved these changes

2022-09-08 15:18 UTC, merged