Run all tests
Tiny-Home-Consulting/Dependiject pull request #33
Opened 2022-09-21 14:23 UTC by bbrk24

## Issue Link

Fixes #31

## Overview of Changes

This PR adds a script to run all tests, including the example projects' tests, from the command line. It also entails a change to the pbxproj files to allow the test script to generate mocks automatically.

### Anything you want to highlight?

N/A

## Test Plan

Run the test script.

2022-09-21 17:33 UTC, Ljgleeson approved these changes

2022-09-21 19:41 UTC, NicholasChase reviewed
Tests require Cocoapods 1.11.3 to successfully pass

2022-09-21 19:59 UTC, bbrk24 commented
> Tests require Cocoapods 1.11.3 to successfully pass

This is due to a bug in earlier versions of CocoaPods. In 1.11.2, the tests will fail the first time but pass the second time.

2022-09-22 13:06 UTC, NicholasChase approved these changes

2022-09-22 20:33 UTC, wboyd600 requested changes

2022-09-22 20:33 UTC, wboyd600 commented on runtests.sh
> +swift test
I had a hard time determining if the tests we're actually passing when I ran it. I understand now that they pass if everything runs and you don't get a red "** TEST FAILED **". I think if we could get that output to be consistent with the `swift test` result it would be easier to tell if they failed. Likewise it would be easier to tell they passed if the opposite happened (like just outputting a "** TEST FAILED **"). I'm sure it's also possible to terminal vomit elsewhere and only display custom messages but I think that might be asking for too much and we can always iterate on it. But for now, I think it would be ideal if we got a consistent "TEST FAILED" and "TEST PASSED" as the final output. 

With that being said, kudos to you -- it's super cool we can do all of this with one command.

2022-09-23 16:53 UTC, wboyd600 approved these changes

2022-09-23 16:54 UTC, merged