Add registration of external constants
Tiny-Home-Consulting/Dependiject pull request #34
Opened 2022-09-22 16:01 UTC by bbrk24

## Issue Link

Fixes #21 

## Overview of Changes

This PR adds the `ConstantRegistration` type, and new initializers to `Service` and `MultitypeService`, to register existing objects as dependencies.

### Anything you want to highlight?

For better organization, I changed `TransientRegistration` to a struct (as noted in the **`Remark`** above it) and put it next to `ConstantRegistration`. This looks a little weird in the diff.

## Test Plan

I added new tests to check the new initializers, in the same format as the existing tests. Some of the tests for which scope is less important (such as the registration name tests) I also changed to use this.

2022-09-23 20:23 UTC, NicholasChase approved these changes

2022-09-23 20:24 UTC, NicholasChase reviewed
Conflicts in the change log

2022-09-23 20:59 UTC, Ljgleeson commented on Dependiject/Registration.swift
> +    internal let name: String?
Part of me wishes we could make this a struct of its own as they are reused in each struct and class but also it isn't that big of a deal. Just seeing a lot of similar code

2022-09-27 18:27 UTC, Ljgleeson requested changes
Theres still a conflict in the changelog

2022-09-27 18:33 UTC, Ljgleeson approved these changes

2022-09-29 18:50 UTC, wboyd600 commented on Dependiject/Registration.swift
> +    internal let name: String?
It's protocol conformance -- so it's similar code by enforcement

2022-09-29 19:29 UTC, wboyd600 approved these changes

2022-09-29 19:29 UTC, merged