Add error for weak service resolved by singleton
Tiny-Home-Consulting/Dependiject pull request #40
Opened 2022-09-30 19:16 UTC by bbrk24

## Issue Link

Fixes #32

## Overview of Changes

This PR adds a check for resolving a weak service as a dependency for a singleton. Such a resolution promotes the weak service to itself be a singleton, unless the singleton stores it in a weak property.

Since it is possible for this to work as declared, it is possible to opt out of the check.

### Anything you want to highlight?

I'm not completely satisfied with how `WeakRegistration` accesses the options. I'm open to suggestions in this regard.

## Test Plan

Removing the line `Factory.options.singletonAcceptsWeak = true` from the new test should cause it to crash, unless `Factory.options.mode` is set to `.never`.

2022-10-03 19:18 UTC, Ljgleeson commented on Dependiject/Registration.swift
> +                options.singletonAcceptsWeak || !resolver.isResolvingForSingleton(),
Why do we need both singletonAcceptsWeak and isResolvingForSingleton() exactly? It seems like you are using either or for checking and this could be simplified by just using 'singletonAcceptsWeak' and then you can remove the three resolving functions that were added in this pr. I feel like I'm more likely missing something here

2022-10-03 19:18 UTC, Ljgleeson commented on Dependiject/Registration.swift
> +            resolver.endResolvingForSingleton()
Wouldn't this result in `isResolvingForSingleton()` always returning false since `singletonDepth` will always balance out to 0?

2022-10-03 19:27 UTC, bbrk24 commented on Dependiject/Registration.swift
> +            resolver.endResolvingForSingleton()
No. Imagine a setup like the following:

```swift
class Foo {}
class Bar {}
class Baz {
    var bar: Bar
    var foo: Foo
}

func main() {
    Factory.register {
        Service(.weak, Foo.self) { _ in // <- callback for WeakRegistration
            // [1]
            Foo()
        }

        Service(.singleton, Bar.self) { _ in // <- callback for SingletonRegistration
            // [2]
            Bar()
        }

        Service(.singleton, Baz.self) { r in // <- callback for SingletonRegistration
            // [3]
            Baz(bar: r.resolve(), foo: r.resolve())
        }
    }
}
```

Before closure [3] is called, this will call `beginResolvingForSingleton()`. Thus, inside of block [3], the value of `singletonDepth` is 1.

The first call to `r.resolve()` will wind up at closure [2]. Here, `singletonDepth` is now 2 -- one for Baz and one for Bar. This closure exits, the singleton depth is decremented, and we end back up inside [3].

The second call to `r.resolve()` will then reach the WeakRegistration corresponding to Foo. If block [1] were entered, `singletonDepth` here would still be 1. However, the WeakRegistration sees that it's not 0 and raises an error.

Assuming that error is not raised, however, block [1] runs normally, and then returns to block [3]. Block [3] finally exits, makes its `endResolvingForSingleton()` call, and `singletonDepth` is once again zero.

I had to make this a depth number rather than a simple true/false. If it were a boolean, the end of block [2] would set it to false, and block [1] would incorrectly see that it is not being used by a singleton.

2022-10-03 19:29 UTC, bbrk24 commented on Dependiject/Registration.swift
> +                options.singletonAcceptsWeak || !resolver.isResolvingForSingleton(),
Weak registrations are not generally allowed inside singletons. So originally this call looked more like
```swift
assert(!resolver.isResolvingForSingleton())
```
However, I wanted this to be configurable. If `singletonAcceptsWeak` is set to true, it allows the weak registration without checking `isResolvingForSingleton()`.

2022-10-03 20:17 UTC, bbrk24 commented on Dependiject/Factory.swift
> +    ) {
I originally provided a default value for `singletonAcceptsWeak` so that calls to this initializer written using version 0.2 would still work if this feature landed in 0.3 or a hypothetical 0.4. However, it seems likely that the next release will be 1.0, so I could remove this default argument. Alternatively, I could add default values for all three.

2022-10-04 19:57 UTC, Ljgleeson commented on Dependiject/Registration.swift
> +            resolver.endResolvingForSingleton()
Okay yeah that clears it up for me, thanks.

2022-10-04 20:27 UTC, bbrk24 commented on Dependiject/Factory.swift
> +    ) {
As discussed in person, I will move the defaults for the other two from the initial value for `options` to the initializer here.

2022-10-04 20:35 UTC, bbrk24 commented on Dependiject/Registration.swift
> +            resolver.endResolvingForSingleton()
I'm going to leave this as unresolved so it's more visible. This part wasn't even clear to me when I was first thinking about this problem.

2022-10-04 20:38 UTC, Ljgleeson approved these changes

2022-10-05 15:02 UTC, NicholasChase commented on Dependiject/Registration.swift
> +            resolver.endResolvingForSingleton()
Very helpful explanation

2022-10-05 15:18 UTC, NicholasChase approved these changes

2022-10-05 19:25 UTC, wboyd600 requested changes

2022-10-05 19:25 UTC, wboyd600 commented on Dependiject/Registration.swift
> +                options.singletonAcceptsWeak || !resolver.isResolvingForSingleton(),
This is only warning when you're creating a new instance as opposed to creating a new one

2022-10-05 19:34 UTC, bbrk24 commented on Dependiject/Registration.swift
> +                options.singletonAcceptsWeak || !resolver.isResolvingForSingleton(),
This is worded confusingly but we've discussed this in-person and I know what you mean.

2022-10-05 20:22 UTC, wboyd600 commented
I think we can get around this
```
  Factory.shared.beginResolvingForSingleton()
        Factory.register {
            Service(.transient, DataFetcher.self) { _ in
                DataFetcherImplementation()
            }
        }
```
immediately breaking by making those functions internal on Factory, and upcasting our Resolver to the Factory or a protocol that can access those functions so we don't expose singleton registration implementation details to the end user

2022-10-06 21:13 UTC, wboyd600 approved these changes

2022-10-06 21:13 UTC, wboyd600 commented on Dependiject/Registration.swift
> +            let options = Factory.options
I don't know how else we'd access the options

2022-10-06 21:14 UTC, merged