added example for testing protocols that extend AnyObservableObject
Tiny-Home-Consulting/Dependiject pull request #8
Opened 2022-05-09 18:39 UTC by wboyd600

## Issue Link

Fixes #7 

## Overview of Changes

This PR adds an example for Mocking a protocol that extends `AnyObservableObject`, and refactors view / viewModel code to make the example tests meaningful.

2022-05-09 20:06 UTC, wboyd600 commented on iOS 13 Example/Dependiject/Services.swift
> +import Combine
I've been trying to find a way to get this to import automatically. Mockingbird doesn't automatically import Combine in its generate mocks file and it seems weird having to 
`import Combine`
in some random place.

2022-05-10 16:03 UTC, wboyd600 commented on iOS 13 Example/Dependiject/Services.swift
> +import Combine
After doing some research, it seems to be related to this Mockingbird [issue.](https://github.com/birdrides/mockingbird/issues/268) I've tried using different mockingbird configure options like linking to the Dependiject source like
```
$ mockingbird configure MyAppTests \
    --project /path/to/MyApp.xcodeproj \
    --srcproject /path/to/ExternalFramework.xcodeproj \
    -- \
    --targets ExternalFramework
```
and it didn't work still. 

The workaround listed in the issue is to do what we're already doing, adding `import Combine` in the source file being mocked so Mockingbird will include it in the header section of the generated mocks.

2022-05-10 16:10 UTC, wboyd600 commented on iOS 13 Example/Dependiject/Services.swift
> +import Combine
@bbrk24 I see you self-requested a review. If you have any opinions on this issue feel free to chime in. I was also checking to make sure we didn't have to add any other support files for the other XCUI stuff (like ErasedObservableObject.swift and Store.swift) because they aren't protocols, right?

2022-05-10 18:10 UTC, bbrk24 commented on iOS 13 Example/Dependiject/Services.swift
> +import Combine
> and it seems weird having to
> `import Combine`
> in some random place.

I think it's only weird because we're used to being able to chain imports. We're used to being able to have `import UIKit` imply `import Foundation`, for example.

However, this doesn't always work with SwiftUI. Even if you have a PreviewProvider, if you don't explicitly `import SwiftUI` then you don't get a live preview. As soon as we drop the assumption that transitive imports work, this isn't weird at all. I think we should just `import Combine` wherever we use `@Published`.

> I was also checking to make sure we didn't have to add any other support files for the other XCUI stuff

We don't have to mock `Store` since it's a property wrapper, and we don't have to mock `ErasedObservableObject` since it's just an implementation detail of `Store`.

2022-05-10 18:29 UTC, bbrk24 requested changes
I'm quite surprised the tests pass, given that you don't stub the DataStateManager, but if it works it works I suppose.

I only left each comment on one example or the other, but most if not all of them apply to both.

2022-05-10 18:29 UTC, bbrk24 commented on iOS 13 Example/MockingbirdSupport/Combine/ObservableObjectPublisher.swift
> +        public var description: String { get }
There's really no reason to have all the doc comments here. I think we should remove them to cut down on the file size.

2022-05-10 18:29 UTC, bbrk24 commented on iOS 13 Example/Dependiject/ContentView.swift
>  }
Rather than doing the content view preview like this, I think we should have previews for `PrimaryView` and `SecondaryView` in their respective files, and no preview in this file at all.

2022-05-10 18:29 UTC, bbrk24 commented on iOS 13 Example/Dependiject/Services.swift
> +    init()
Maybe there's something I'm missing, but I don't see the point of requiring the init in this protocol.

2022-05-10 18:29 UTC, bbrk24 commented on iOS 14 Example/Dependiject_Example/SecondaryViewModel.swift
> +protocol SecondaryViewModel: AnyObservableObject {
The secondary view model doesn't have any published properties, so it doesn't need to
- be marked `@Store` at the use site
- have the protocol inherit from `AnyObservableObject`
- have the implementation conform to `ObservableObject`
If you're going to remove these one at a time, though, remove them in the order I just listed -- I think it won't run if you remove `ObservableObject` without removing `AnyObservableObject`, or remove `AnyObservableObject` without removing `@Store`.

2022-05-10 20:10 UTC, wboyd600 commented on iOS 14 Example/Dependiject_Example/SecondaryViewModel.swift
> +protocol SecondaryViewModel: AnyObservableObject {
Good point. I've updated the examples accordingly. Additionally, I think these suggestions improve the example projects because it highlights the difference between Published injections and normal non-property wrapped injections in a SwiftUI view

2022-05-11 18:17 UTC, bbrk24 approved these changes

2022-05-11 19:37 UTC, Ljgleeson approved these changes

2022-05-11 19:37 UTC, Ljgleeson commented on iOS 13 Example/MockingbirdSupport/Combine/ObservableObjectPublisher.swift
> +//
Should this be licensed under Tiny home or should it be Apple since all the content is from them?

2022-05-12 15:41 UTC, wboyd600 commented on iOS 13 Example/MockingbirdSupport/Combine/ObservableObjectPublisher.swift
> +//
I'm really not sure

2022-09-06 17:27 UTC, wboyd600 commented on iOS 13 Example/MockingbirdSupport/Combine/ObservableObjectPublisher.swift
> +//
@bbrk24 I was about to check re-check what mockingbird did for theirs. 

But I'm pretty sure we came to the conclusion that it was fine to keep the license as TinyHome since that's what Mockingbird was doing.

2022-09-06 17:41 UTC, bbrk24 commented on iOS 13 Example/MockingbirdSupport/Combine/ObservableObjectPublisher.swift
> +//
I would agree. Though, the branch needs to be rebased either way.

2022-09-06 20:10 UTC, bbrk24 approved these changes

2022-09-06 20:10 UTC, bbrk24 commented on iOS 13 Example/Tests/PrimaryViewModelTests.swift
> +        verify(mockDataStateManager.setDataState(confirmed: true)).wasCalled(1)
Mockingbird provides `once` specifically for this. We don't need to use this but it might improve legibility.

2022-09-06 20:10 UTC, bbrk24 commented on iOS 14 Example/Dependiject_ExampleTests/PrimaryViewModelTests.swift
> +        verify(mockDataStateManager.setDataState(confirmed: true)).wasCalled(1)
same as above

2022-09-07 18:45 UTC, merged